/**
 * Planner - Coverage Target → TestPlan
 *
 * Three-level architecture:
 *   1. Deterministic Planner - Pure code, no LLM, for simple/known patterns
 *   2. Template Planner - Registry of UI pattern handlers
 *   3. LLM Planner - For complex/unknown/business logic
 *
 * Core principle:
 *   Planner decides "HOW to test", not "WHAT to test".
 *   "WHAT to test" is decided by CoverageModel + CoveragePolicy.
 *
 * Flow:
 *   CoverageTarget + Surface + Policy
 *         ↓
 *   PlannerSelector (risk + complexity + test type)
 *         ↓
 *   Deterministic / Template / LLM
 *         ↓
 *   TestPlan
 */

import type {
  CoverageModel,
  CoverageModule,
  CoverageSurface,
  CoverageFeature,
  CoverageTarget,
  CoveragePolicy,
  TestType,
  PriorityLevel,
  ScenarioType,
  FeatureType,
} from './coverage.js';
import {
  COVERAGE_POLICIES,
  effectivePriority,
  isFeatureCovered,
} from './coverage.js';
import type { SurfaceSignature } from './surface-signature.js';

// ─── TestPlan Types ──────────────────────────────────────────────────────────

/**
 * A single step in a test plan.
 * Richer than the old TestPlanItem - carries context for execution.
 */
export interface TestPlanStep {
  /** Human-readable description of what to do */
  description: string;
  /** The tool to use (browser_click, browser_fill_form, etc.) */
  tool?: string;
  /** Expected tool arguments (partial, will be filled at execution) */
  toolArgs?: Record<string, unknown>;
  /** What to verify after this step */
  expectedOutcome?: string;
  /** Which scenario this step serves */
  scenarioType?: ScenarioType;
}

/**
 * A test plan generated by a planner.
 * This is the OUTPUT of the planner, consumed by the execution engine.
 */
export interface TestPlan {
  /** Which surface this plan is for */
  surfaceKey: string;
  /** Which feature this plan targets */
  featureKey: string;
  /** Which scenario type this plan covers */
  scenarioType: ScenarioType;
  /** Which planner generated this */
  plannerLevel: 'deterministic' | 'template' | 'llm';
  /** The actual steps to execute */
  steps: TestPlanStep[];
  /** Priority of this plan */
  priority: PriorityLevel;
}

// ─── Planner Interface ───────────────────────────────────────────────────────

/**
 * Base planner interface.
 * All planners (Deterministic, Template, LLM) implement this.
 */
export interface Planner {
  /** Unique name for debugging/logging */
  name: string;

  /**
   * Can this planner handle the given target?
   * Called by PlannerSelector to choose the right planner.
   */
  canHandle(
    surface: CoverageSurface,
    feature: CoverageFeature,
    target: CoverageTarget,
    signature?: SurfaceSignature
  ): boolean;

  /**
   * Generate a test plan for the given target.
   * Returns steps that the execution engine will follow.
   */
  generate(
    surface: CoverageSurface,
    feature: CoverageFeature,
    target: CoverageTarget,
    policy: CoveragePolicy,
    signature?: SurfaceSignature
  ): TestPlan;
}

// ─── Risk Score ──────────────────────────────────────────────────────────────

/**
 * Calculate risk score for a surface/feature combination.
 * Used by PlannerSelector to choose the right planner level.
 *
 * Currently implemented factors:
 *   - Business Criticality (0-4) — from effectivePriority(module, surface, feature)
 *   - Data Mutation (0-3) — button/form/upload, higher for destructive actions
 *   - State Complexity (0-3) — form field count (only for feature.type === 'form')
 *   - Form Complexity (0-3) — complex field types (dropdown/upload/checkbox/radio)
 *   - Unknown (0-2) — feature.type === 'unknown'
 *
 * Not yet implemented (reserved for Phase 4 integration):
 *   - Navigation Depth (0-2) — requires workflow context
 *   - Dependency (0-2) — requires cross-surface analysis
 *
 * Note: State Complexity and Form Complexity may overlap for forms with many
 * complex fields. This is intentional — both dimensions contribute to risk.
 */
export function calculateRiskScore(
  surface: CoverageSurface,
  feature: CoverageFeature,
  module: CoverageModule
): number {
  let score = 0;

  // Business Criticality (0-4)
  const priority = effectivePriority(module, surface, feature);
  switch (priority) {
    case 'critical': score += 4; break;
    case 'high': score += 3; break;
    case 'normal': score += 1; break;
    case 'low': score += 0; break;
  }

  // Data Mutation (0-3)
  const mutationFeatures = ['button', 'form', 'upload'];
  if (mutationFeatures.includes(feature.type)) {
    // Check if it's a destructive action
    const destructiveKeywords = ['delete', 'remove', 'destroy', 'drop', 'clear', 'reset',
      '删除', '移除', '清除', '清空'];
    const name = feature.name.toLowerCase();
    if (destructiveKeywords.some(k => name.includes(k))) {
      score += 3;
    } else {
      score += 2;
    }
  }

  // State Complexity (0-3)
  // Forms with many fields have higher state complexity
  if (feature.type === 'form') {
    const fieldCount = surface.features.filter(f =>
      ['text-input', 'number-input', 'checkbox', 'radio', 'dropdown', 'upload'].includes(f.type)
    ).length;
    if (fieldCount > 10) score += 3;
    else if (fieldCount > 5) score += 2;
    else if (fieldCount > 0) score += 1;
  }

  // Form Complexity (0-3) - based on field types
  const complexFieldTypes = ['dropdown', 'upload', 'checkbox', 'radio'];
  const hasComplexFields = surface.features.some(f => complexFieldTypes.includes(f.type));
  if (hasComplexFields) {
    const complexCount = surface.features.filter(f => complexFieldTypes.includes(f.type)).length;
    if (complexCount > 5) score += 3;
    else if (complexCount > 2) score += 2;
    else score += 1;
  }

  // Navigation Depth (0-2) — not yet implemented, requires workflow context
  // Dependency (0-2) — not yet implemented, requires cross-surface analysis

  // Unknown (0-2) - if feature type is unknown
  if (feature.type === 'unknown') {
    score += 2;
  }

  return score;
}

// ─── Planner Selector ────────────────────────────────────────────────────────

/**
 * Select the appropriate planner based on risk, complexity, and test type.
 */
export function selectPlannerLevel(
  riskScore: number,
  featureType: FeatureType,
  testType: TestType
): 'deterministic' | 'template' | 'llm' {
  // Test type affects thresholds
  const thresholds: Record<TestType, { template: number; llm: number }> = {
    smoke:        { template: 4, llm: 8 },
    confirmation: { template: 3, llm: 6 },
    acceptance:   { template: 2, llm: 5 },
    full:         { template: 1, llm: 3 },
  };

  const t = thresholds[testType];

  // Simple feature types that are always deterministic (regardless of risk)
  const deterministicTypes: FeatureType[] = ['link', 'tab', 'navigation'];
  if (deterministicTypes.includes(featureType)) {
    return 'deterministic';
  }

  if (riskScore < t.template) return 'deterministic';
  if (riskScore < t.llm) return 'template';
  return 'llm';
}

// ─── Deterministic Planner ───────────────────────────────────────────────────

/**
 * Deterministic planner for simple, well-known patterns.
 * Pure code, no LLM, minimal cost.
 */
const deterministicPlanner: Planner = {
  name: 'deterministic',

  canHandle(surface, feature, target): boolean {
    // Handle simple interaction types
    const simpleTypes: FeatureType[] = ['link', 'tab', 'navigation', 'checkbox', 'radio', 'pagination'];
    return simpleTypes.includes(feature.type);
  },

  generate(surface, feature, target): TestPlan {
    const steps: TestPlanStep[] = [];

    switch (feature.type) {
      case 'link':
        steps.push({
          description: `Click link "${feature.name}" and verify navigation`,
          tool: 'browser_click',
          expectedOutcome: 'Page navigates to new URL or content changes',
          scenarioType: target.scenarioType,
        });
        break;

      case 'tab':
        steps.push({
          description: `Click tab "${feature.name}" and verify it becomes active`,
          tool: 'browser_click',
          expectedOutcome: `Tab "${feature.name}" is now selected/active`,
          scenarioType: target.scenarioType,
        });
        break;

      case 'navigation':
        steps.push({
          description: `Navigate via "${feature.name}" and verify destination`,
          tool: 'browser_click',
          expectedOutcome: 'Navigation succeeds, new page loads',
          scenarioType: target.scenarioType,
        });
        break;

      case 'checkbox':
        steps.push({
          description: `Toggle checkbox "${feature.name}" and verify state change`,
          tool: 'browser_check',
          expectedOutcome: `Checkbox "${feature.name}" state changes`,
          scenarioType: target.scenarioType,
        });
        break;

      case 'radio':
        steps.push({
          description: `Select radio button "${feature.name}" and verify selection`,
          tool: 'browser_click',
          expectedOutcome: `Radio button "${feature.name}" is selected`,
          scenarioType: target.scenarioType,
        });
        break;

      case 'pagination':
        if (target.scenarioType === 'normal') {
          steps.push({
            description: `Click next page and verify page change`,
            tool: 'browser_click',
            expectedOutcome: 'Page number changes, content updates',
            scenarioType: target.scenarioType,
          });
        } else if (target.scenarioType === 'boundary') {
          steps.push({
            description: `Navigate to first page, then last page, verify boundaries`,
            tool: 'browser_click',
            expectedOutcome: 'Boundary pages load correctly',
            scenarioType: target.scenarioType,
          });
        }
        break;

      default:
        steps.push({
          description: `Interact with "${feature.name}" (${feature.type})`,
          scenarioType: target.scenarioType,
        });
    }

    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'deterministic',
      steps,
      priority: target.priority.level,
    };
  },
};

// ─── Template Registry ───────────────────────────────────────────────────────

/**
 * Template planner interface.
 * Each template handles a specific UI pattern.
 */
export interface TemplatePlanner {
  name: string;
  canHandle(surface: CoverageSurface, feature: CoverageFeature, target: CoverageTarget): boolean;
  generate(surface: CoverageSurface, feature: CoverageFeature, target: CoverageTarget): TestPlan;
}

// ─── Form Template ───────────────────────────────────────────────────────────

const formTemplate: TemplatePlanner = {
  name: 'form',

  canHandle(surface, feature, _target): boolean {
    // Only handle feature.type === 'form'.
    // Button-type features (including CRUD buttons) are NOT handled here —
    // they are handled by crudTemplate or deterministicPlanner.
    return feature.type === 'form';
  },

  generate(surface, feature, target): TestPlan {
    const steps: TestPlanStep[] = [];

    if (target.scenarioType === 'normal') {
      // Fill all fields with valid data
      const formFields = surface.features.filter(f =>
        ['text-input', 'number-input', 'checkbox', 'radio', 'dropdown'].includes(f.type)
      );

      for (const field of formFields) {
        steps.push({
          description: `Fill "${field.name}" (${field.type}) with valid data`,
          tool: field.type === 'checkbox' ? 'browser_check' :
                field.type === 'radio' ? 'browser_click' :
                field.type === 'dropdown' ? 'browser_select_option' : 'browser_type',
          scenarioType: 'normal',
        });
      }

      // Find submit button
      const submitButton = surface.features.find(f =>
        f.type === 'button' && (
          /submit|提交|保存|确定|确认|create|创建|save/i.test(f.name)
        )
      );

      if (submitButton) {
        steps.push({
          description: `Click "${submitButton.name}" to submit`,
          tool: 'browser_click',
          expectedOutcome: 'Form submitted successfully',
          scenarioType: 'normal',
        });
      }

      steps.push({
        description: 'Verify submission result (success message or redirect)',
        expectedOutcome: 'Success indication visible',
        scenarioType: 'normal',
      });
    }

    if (target.scenarioType === 'validation') {
      // Test required field validation
      const requiredFields = surface.features.filter(f =>
        ['text-input', 'number-input', 'dropdown'].includes(f.type)
      );

      if (requiredFields.length > 0) {
        steps.push({
          description: 'Clear all required fields and submit',
          tool: 'browser_click',
          expectedOutcome: 'Validation errors shown for required fields',
          scenarioType: 'validation',
        });
      }

      // Test invalid formats
      for (const field of requiredFields.slice(0, 3)) {
        steps.push({
          description: `Enter invalid data in "${field.name}" and submit`,
          tool: 'browser_type',
          expectedOutcome: `Validation error for "${field.name}"`,
          scenarioType: 'validation',
        });
      }
    }

    if (target.scenarioType === 'boundary') {
      // Test boundary values
      const textFields = surface.features.filter(f => f.type === 'text-input');
      for (const field of textFields.slice(0, 2)) {
        steps.push({
          description: `Enter maximum length value in "${field.name}"`,
          tool: 'browser_type',
          expectedOutcome: 'Value accepted or length limit enforced',
          scenarioType: 'boundary',
        });
      }
    }

    if (target.scenarioType === 'error') {
      steps.push({
        description: 'Submit form with data that triggers server error',
        expectedOutcome: 'Error message displayed gracefully',
        scenarioType: 'error',
      });
    }

    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'template',
      steps,
      priority: target.priority.level,
    };
  },
};

// ─── Table Template ──────────────────────────────────────────────────────────

const tableTemplate: TemplatePlanner = {
  name: 'table',

  canHandle(surface, feature, target): boolean {
    return feature.type === 'table';
  },

  generate(surface, feature, target): TestPlan {
    const steps: TestPlanStep[] = [];

    if (target.scenarioType === 'normal') {
      steps.push({
        description: `Verify table "${feature.name}" displays data correctly`,
        expectedOutcome: 'Table shows rows with expected columns',
        scenarioType: 'normal',
      });
      steps.push({
        description: 'Click a row and verify detail view or selection',
        tool: 'browser_click',
        expectedOutcome: 'Row selected or detail shown',
        scenarioType: 'normal',
      });
    }

    if (target.scenarioType === 'boundary') {
      steps.push({
        description: 'Check table with empty data or many pages',
        expectedOutcome: 'Empty state or pagination works correctly',
        scenarioType: 'boundary',
      });
    }

    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'template',
      steps,
      priority: target.priority.level,
    };
  },
};

// ─── Search Template ─────────────────────────────────────────────────────────

const searchTemplate: TemplatePlanner = {
  name: 'search',

  canHandle(surface, feature, target): boolean {
    return feature.type === 'search';
  },

  generate(surface, feature, target): TestPlan {
    const steps: TestPlanStep[] = [];

    if (target.scenarioType === 'normal') {
      steps.push({
        description: `Enter search term in "${feature.name}" and submit`,
        tool: 'browser_type',
        expectedOutcome: 'Search results displayed',
        scenarioType: 'normal',
      });
      steps.push({
        description: 'Verify search results match the query',
        expectedOutcome: 'Results contain matching items',
        scenarioType: 'normal',
      });
    }

    if (target.scenarioType === 'validation') {
      steps.push({
        description: 'Enter special characters or empty string in search',
        tool: 'browser_type',
        expectedOutcome: 'Graceful handling (error message or empty results)',
        scenarioType: 'validation',
      });
    }

    if (target.scenarioType === 'boundary') {
      steps.push({
        description: 'Enter very long search string',
        tool: 'browser_type',
        expectedOutcome: 'Input truncated or handled gracefully',
        scenarioType: 'boundary',
      });
    }

    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'template',
      steps,
      priority: target.priority.level,
    };
  },
};

// ─── Upload Template ─────────────────────────────────────────────────────────

const uploadTemplate: TemplatePlanner = {
  name: 'upload',

  canHandle(surface, feature, target): boolean {
    return feature.type === 'upload';
  },

  generate(surface, feature, target): TestPlan {
    const steps: TestPlanStep[] = [];

    if (target.scenarioType === 'normal') {
      steps.push({
        description: `Upload a valid file via "${feature.name}"`,
        expectedOutcome: 'File uploaded successfully',
        scenarioType: 'normal',
      });
    }

    if (target.scenarioType === 'validation') {
      steps.push({
        description: `Try to upload invalid file type via "${feature.name}"`,
        expectedOutcome: 'Validation error for invalid file type',
        scenarioType: 'validation',
      });
    }

    if (target.scenarioType === 'error') {
      steps.push({
        description: `Try to upload oversized file via "${feature.name}"`,
        expectedOutcome: 'Error message for file size limit',
        scenarioType: 'error',
      });
    }

    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'template',
      steps,
      priority: target.priority.level,
    };
  },
};

// ─── Modal Template ──────────────────────────────────────────────────────────

const modalTemplate: TemplatePlanner = {
  name: 'modal',

  canHandle(surface, feature, target): boolean {
    return feature.type === 'modal';
  },

  generate(surface, feature, target): TestPlan {
    const steps: TestPlanStep[] = [];

    if (target.scenarioType === 'normal') {
      steps.push({
        description: `Open modal "${feature.name}" and verify content`,
        tool: 'browser_click',
        expectedOutcome: 'Modal opens with expected content',
        scenarioType: 'normal',
      });
      steps.push({
        description: 'Close modal and verify it disappears',
        tool: 'browser_click',
        expectedOutcome: 'Modal closed',
        scenarioType: 'normal',
      });
    }

    if (target.scenarioType === 'error') {
      steps.push({
        description: 'Trigger error state in modal and verify error handling',
        expectedOutcome: 'Error displayed gracefully in modal',
        scenarioType: 'error',
      });
    }

    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'template',
      steps,
      priority: target.priority.level,
    };
  },
};

// ─── CRUD Template ───────────────────────────────────────────────────────────

const crudTemplate: TemplatePlanner = {
  name: 'crud',

  canHandle(surface, feature, target): boolean {
    // Handle button features that look like CRUD operations
    if (feature.type !== 'button') return false;
    const name = feature.name.toLowerCase();
    return /create|new|add|edit|update|delete|remove|创建|新增|添加|编辑|修改|删除/i.test(name);
  },

  generate(surface, feature, target): TestPlan {
    const steps: TestPlanStep[] = [];
    const name = feature.name.toLowerCase();

    if (/create|new|add|创建|新增|添加/.test(name)) {
      if (target.scenarioType === 'normal') {
        steps.push({
          description: `Click "${feature.name}" to open creation form`,
          tool: 'browser_click',
          expectedOutcome: 'Creation form or dialog appears',
          scenarioType: 'normal',
        });
      }
    } else if (/edit|update|编辑|修改/.test(name)) {
      if (target.scenarioType === 'normal') {
        steps.push({
          description: `Click "${feature.name}" to edit`,
          tool: 'browser_click',
          expectedOutcome: 'Edit form pre-filled with existing data',
          scenarioType: 'normal',
        });
      }
    } else if (/delete|remove|删除|移除/.test(name)) {
      if (target.scenarioType === 'normal') {
        steps.push({
          description: `Click "${feature.name}"`,
          tool: 'browser_click',
          expectedOutcome: 'Confirmation dialog appears',
          scenarioType: 'normal',
        });
        steps.push({
          description: 'Confirm deletion',
          tool: 'browser_click',
          expectedOutcome: 'Item removed from list',
          scenarioType: 'normal',
        });
      }
    }

    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'template',
      steps,
      priority: target.priority.level,
    };
  },
};

// ─── Template Registry ───────────────────────────────────────────────────────

/**
 * Registry of all template planners.
 * Order matters: more specific templates first.
 * CRUD must come before form because CRUD buttons are also buttons.
 */
const TEMPLATE_PLANNERS: TemplatePlanner[] = [
  crudTemplate,     // CRUD operations (most specific for buttons)
  formTemplate,     // Generic forms
  tableTemplate,
  searchTemplate,
  uploadTemplate,
  modalTemplate,
];

/**
 * Template planner that delegates to the registry.
 */
const templatePlanner: Planner = {
  name: 'template',

  canHandle(surface, feature, target): boolean {
    return TEMPLATE_PLANNERS.some(t => t.canHandle(surface, feature, target));
  },

  generate(surface, feature, target): TestPlan {
    // Find the first matching template
    const matching = TEMPLATE_PLANNERS.find(t => t.canHandle(surface, feature, target));
    if (matching) {
      return matching.generate(surface, feature, target);
    }

    // Fallback: generic template
    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'template',
      steps: [{
        description: `Test "${feature.name}" (${feature.type}) - ${target.scenarioType} scenario`,
        scenarioType: target.scenarioType,
      }],
      priority: target.priority.level,
    };
  },
};

// ─── LLM Planner ─────────────────────────────────────────────────────────────

/**
 * LLM planner for complex/unknown scenarios.
 * This is a placeholder - actual implementation will call LLM.
 *
 * The LLM receives:
 *   - Surface context (what's on the page)
 *   - Coverage target (what needs to be tested)
 *   - Already covered scenarios
 *   - Available controls
 *
 * And generates specific test steps.
 */
const llmPlanner: Planner = {
  name: 'llm',

  canHandle(): boolean {
    // LLM can handle anything
    return true;
  },

  generate(surface, feature, target): TestPlan {
    // Placeholder: In real implementation, this will call LLM
    // For now, return a generic plan that indicates LLM is needed
    return {
      surfaceKey: target.surfaceKey,
      featureKey: target.featureKey,
      scenarioType: target.scenarioType,
      plannerLevel: 'llm',
      steps: [{
        description: `[LLM] Analyze and test "${feature.name}" (${feature.type}) for ${target.scenarioType} scenario on surface "${surface.title ?? surface.key}"`,
        scenarioType: target.scenarioType,
      }],
      priority: target.priority.level,
    };
  },
};

/**
 * Build the prompt for LLM planner.
 * This is the structured input that LLM receives.
 */
export function buildLLMPlannerPrompt(
  surface: CoverageSurface,
  feature: CoverageFeature,
  target: CoverageTarget,
  module: CoverageModule,
  alreadyCovered: string[]
): string {
  const availableControls = surface.features.map(f =>
    `- ${f.name} (${f.type})`
  ).join('\n');

  return `You are testing a web application. Generate specific test steps for the following target.

## Surface Context
- Module: ${module.name}
- Surface: ${surface.title ?? surface.key}
- URL: ${surface.url ?? 'unknown'}

## Coverage Target
- Feature: ${feature.name} (${feature.type})
- Scenario: ${target.scenarioType}
- Priority: ${target.priority.level}

## Already Covered
${alreadyCovered.length > 0 ? alreadyCovered.map(s => `- ${s}`).join('\n') : 'None yet'}

## Available Controls on this Surface
${availableControls}

## Instructions
Generate 2-5 specific test steps to cover the "${target.scenarioType}" scenario for "${feature.name}".
Each step should include:
1. What action to take (click, type, select, etc.)
2. What element to interact with (by name/label)
3. What to verify after the action

Focus on the ${target.scenarioType} scenario specifically.`;
}

// ─── Planner Selector (Main Entry Point) ─────────────────────────────────────

/**
 * All available planners in priority order.
 */
const PLANNERS: Planner[] = [
  deterministicPlanner,
  templatePlanner,
  llmPlanner,
];

/**
 * Generate a test plan for a coverage target.
 * This is the main entry point for Phase 3.
 *
 * Flow:
 *   1. Find the surface and feature from the model
 *   2. Calculate risk score
 *   3. Select planner level
 *   4. Generate plan
 */
export function generateTestPlan(
  model: CoverageModel,
  target: CoverageTarget,
  policy: CoveragePolicy,
  signature?: SurfaceSignature
): TestPlan | null {
  // Find the module, surface, and feature
  let targetModule: CoverageModule | undefined;
  let targetSurface: CoverageSurface | undefined;
  let targetFeature: CoverageFeature | undefined;

  for (const module of model.modules) {
    for (const surface of module.surfaces) {
      if (surface.key === target.surfaceKey) {
        targetModule = module;
        targetSurface = surface;
        targetFeature = surface.features.find(f => f.key === target.featureKey);
        break;
      }
    }
    if (targetSurface) break;
  }

  if (!targetModule || !targetSurface || !targetFeature) {
    return null;
  }

  // Calculate risk score
  const riskScore = calculateRiskScore(targetSurface, targetFeature, targetModule);

  // Use policy.testType directly instead of inferring from policy shape
  const plannerLevel = selectPlannerLevel(riskScore, targetFeature.type, policy.testType);

  // Find matching planner
  const planner = PLANNERS.find(p => {
    if (plannerLevel === 'deterministic') return p.name === 'deterministic';
    if (plannerLevel === 'template') return p.name === 'template';
    return p.name === 'llm';
  });

  if (!planner) {
    return null;
  }

  // Check if selected planner can handle it
  let plan: TestPlan;
  if (!planner.canHandle(targetSurface, targetFeature, target, signature)) {
    // Fall back to template
    const fallback = PLANNERS.find(p => p.name === 'template');
    if (fallback?.canHandle(targetSurface, targetFeature, target, signature)) {
      plan = fallback.generate(targetSurface, targetFeature, target, policy, signature);
    } else {
      // Fall back to LLM
      plan = llmPlanner.generate(targetSurface, targetFeature, target, policy, signature);
    }
  } else {
    plan = planner.generate(targetSurface, targetFeature, target, policy, signature);
  }

  // Validate the plan — if invalid (e.g. empty steps), fall back to LLM
  if (!validateTestPlan(plan)) {
    plan = llmPlanner.generate(targetSurface, targetFeature, target, policy, signature);
  }

  return plan;
}

/**
 * Generate test plans for ALL uncovered targets.
 *
 * ⚠️ This is a DEBUG / PREVIEW tool, NOT the runtime main path.
 * Runtime should use: selectNextTarget() → generateTestPlan() one at a time.
 * This function exists for:
 *   - Debugging: see what plans would be generated
 *   - Preview: estimate total test scope
 *   - Testing: verify planner behavior across multiple targets
 */
export function generateAllPlans(
  model: CoverageModel,
  policy: CoveragePolicy,
  signatures?: Map<string, SurfaceSignature>
): TestPlan[] {
  const plans: TestPlan[] = [];

  for (const module of model.modules) {
    for (const surface of module.surfaces) {
      for (const feature of surface.features) {
        for (const [scenarioType, coverage] of Object.entries(feature.scenarios) as [ScenarioType, import('./coverage.js').ScenarioCoverage][]) {
          if (coverage.status === 'not_applicable' || coverage.status === 'tested') {
            continue;
          }

          const isRequired = policy.scenarioDepth[scenarioType] === 'required';
          // Use effectivePriority (module → surface → feature max), not just feature.priority
          const effPriority = effectivePriority(module, surface, feature);
          const isCritical = effPriority === 'critical' && policy.risk.criticalFeaturesAlwaysRequired;

          if (isRequired || isCritical) {
            const target: CoverageTarget = {
              surfaceKey: surface.key,
              featureKey: feature.key,
              scenarioType,
              priority: {
                level: effPriority,
                source: feature.priority.source,
              },
            };

            const signature = signatures?.get(surface.key);
            const plan = generateTestPlan(model, target, policy, signature);
            if (plan && validateTestPlan(plan)) {
              plans.push(plan);
            }
          }
        }
      }
    }
  }

  // Sort by priority
  const priorityOrder: Record<PriorityLevel, number> = { critical: 4, high: 3, normal: 2, low: 1 };
  plans.sort((a, b) => priorityOrder[b.priority] - priorityOrder[a.priority]);

  return plans;
}

// ─── Plan Validation ─────────────────────────────────────────────────────────

/**
 * Validate a generated TestPlan.
 * Returns true if the plan is valid and executable.
 * Returns false if the plan is empty or malformed.
 *
 * Checks:
 *   - steps.length > 0
 *   - Every step has a non-empty description
 *   - scenarioType matches across all steps
 *   - plannerLevel is a valid value
 */
export function validateTestPlan(plan: TestPlan): boolean {
  // Must have at least one step
  if (plan.steps.length === 0) return false;

  // Every step must have a description
  if (plan.steps.some(s => !s.description || s.description.trim().length === 0)) return false;

  // scenarioType must be consistent
  const validScenarios: ScenarioType[] = ['normal', 'validation', 'boundary', 'error', 'lifecycle'];
  if (!validScenarios.includes(plan.scenarioType)) return false;

  // plannerLevel must be valid
  const validLevels = ['deterministic', 'template', 'llm'];
  if (!validLevels.includes(plan.plannerLevel)) return false;

  return true;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

// getTestTypeFromPolicy is no longer needed — CoveragePolicy now carries testType directly.
